
http_request:
  description: does a HTTPS request
  fields:
    url:
      description: Number of snapshots you wish to keep.
      examle: "https://homeassistant.io"
    verify_ssl:
      description: tells home-assistant if it should check if the SSL certificate is valid, deaults to true
      example: true
    headers:
      description: a dictionary that contains headers 